### ISSUE TITLE
Installing haystack-ai and farm-haystack together can cause issues

### ISSUE THREAD

**Issue by anakin87** [katanaml/llm-rag-invoice-cpu#1]
Hey, @abaranovskis-redsamurai...

I noticed that this project uses haystack-ai and farm-haystack together.
We recently verified that this causes issues: https://github.com/deepset-ai/haystack/discussions/6684#discussioncomment-8022284

I'm writing this to let you know...

In case you want to maintain this project, you can:
- only use farm-haystack (haystack 1.x) and replace `PyPDFToDocument` with [`PDFToTextConverter`](https://docs.haystack.deepset.ai/docs/file_converters#pdftotextconverter)
- migrate to haystack-ai (haystack 2.0-beta): more effort, requires a rewrite

**Comment by abaranovskis-redsamurai** [comment]
Thanks, I will look into it.
