### ISSUE TITLE
Could you please provide the version of both packages ( "farm-haystack[weaviate]" and "haystack-ai") at the time when they were compatible to each other in the same env?

### ISSUE THREAD

**Issue by gitapii** [katanaml/llm-rag-invoice-cpu#2]
Hi,

I tried to follow the quickstart instruction and installed the requirements via "pip install -r requirements.txt". 

But unlike some months ago when the repo was uploaded, I get unresolved errors as described in "https://github.com/deepset-ai/haystack/issues/6652" or "https://github.com/deepset-ai/haystack/issues/6771". Haystack currently warns the users that farm-haystack and haystack-ai in the same python environment causes problems.

![grafik](https://github.com/katanaml/llm-rag-invoice-cpu/assets/146752936/4bd1b9a2-f738-4e15-a769-47f079f4394d)

Regarding the requirements.txt, you have to install both "farm-haystack[weaviate]" and "haystack-ai", so a parallel installation of them was previously possible, I think.

Could you please provide the version of both packages at the time when they were compatible to each other in the same env? It would be very helpful. Thanks.

Regards,

**Comment by abaranovskis-redsamurai** [comment]
Hey,

This is sample app only and I don't maintain it actively. Soon I will integrating Haystack into our main prod app, it will be maintained from there: https://github.com/katanaml/sparrow
